# Generated by Django 3.0.5 on 2021-12-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
