# Generated by Django 3.0.5 on 2021-12-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20211213_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='pizza',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
